{% set version = "2.0.1" %}

package:
  name: secapr
  version: {{ version }}

source:
  url: https://github.com/AntonelliLab/seqcap_processor/archive/v{{ version }}.tar.gz
  sha256: "d988cd6f45dc50182316b5c556526e5aaa56f0211f0e24d327f07428e09fae75"

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .
  entry_points:
    - secapr = secapr.__main__:main

requirements:
  host:
    - python <3
    - pip
  run:
    - python <3
    - biopython
    - emboss
    - bcftools ==1.8
    - samtools 0.1.19
    - picard
    - seqtk >=1.0.82,<=1.2
    - bwa >=0.7
    - lastz
    - mafft >=7.2
    - muscle
    - trimmomatic ==0.33
    - abyss
    - trinity <=2.3.2
    - fastqc
    - pandas
    - numpy
    - cogent

test:
  imports:
    - secapr
  commands:
    - secapr --version

about:
  home: 'https://github.com/AntonelliLab/seqcap_processor'
  license: MIT
  license_file: LICENSE
  summary: 'Process sequence-capture FASTQ files into alignments for phylogenetic analyses. Integrates allele phasing, producing haplotype alignments.'
